/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package se.yankov.kows

import kotlin.test.Test
import kotlin.test.assertEquals

class CandidateTest {
    @Test
    fun candidatesGeneration() {
        val candidates: Collection<Candidate> = Candidate.permutations(listOf())
        // number of candidates: 10!/6! - 9!/6!
        assertEquals((10 - 1) * 9 * 8 * 7, candidates.size, "Total number of possible numbers")
        assertEquals(Candidate(intArrayOf(1, 0, 2, 3)), candidates.first())
        assertEquals(Candidate(intArrayOf(9, 8, 7, 6)), candidates.last())
    }
}
